# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoFoundationExt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoFoundationExt
  pod 'NSFoundationExtension',:path => '../'

  target 'DemoFoundationExtTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoFoundationExtUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
